package ch.m1m.infra.billing;

import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDDocumentInformation;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import org.apache.pdfbox.util.Version;

import java.awt.*;
import java.io.ByteArrayOutputStream;
import java.io.IOException;

// https://www.tutorialspoint.com/pdfbox/pdfbox_inserting_image.htm

public class PdfGenerator {

    public static void main(String... args) throws IOException {

        String fileName = "/tmp/my_bill.pdf";
        PdfGenerator prog = new PdfGenerator();
        prog.generateSimplePdf(fileName);
    }

    public PDDocument createNewSimplePdf() throws IOException {
        PDDocument document = new PDDocument();

        PDPage page = new PDPage(PDRectangle.A4);

        PDDocumentInformation pdd = document.getDocumentInformation();
        String pdfboxVersion = Version.getVersion();
        pdd.setAuthor("auto generated by apache pdfbox " + pdfboxVersion);
        PDPageContentStream stream = new PDPageContentStream(document, page);

        stream.beginText();
        stream.setFont(PDType1Font.HELVETICA, 12);

            /*
            String text = "1 This is the sample document and we are adding content to it.";
            stream.newLineAtOffset(75, 100);
            stream.showText(text);
            text = "2 This is the sample document and we are adding content to it.";
            stream.newLineAtOffset(25, 50);
            stream.showText(text);
            */

        stream.setLeading(14.5f);
        //Setting the position for the line
        stream.newLineAtOffset(25, 725);

        String text = "1 This is the sample document and we are adding content to it.";

        //Adding text in the form of string
        stream.showText(text);
        stream.newLine();
        text = "2 This is the sample document and we are adding content to it.";
        stream.showText(text);

        stream.endText();

        stream.setNonStrokingColor(Color.DARK_GRAY);
        //stream.setStrokingColor(Color.DARK_GRAY);

        //Drawing a rectangle Y starts with 0 from bottom
        //
        stream.addRect(200, 50, 100, 100);
        stream.fill();

        stream.close();

        document.addPage(page);
        return document;
    }

    public void generateSimplePdf(String fileName) throws IOException {
        PDDocument document = createNewSimplePdf();
        document.save(fileName);
        document.close();

        System.out.println("number of pages: " + document.getNumberOfPages());

            /*
            // convert pdf to byteArray
            ByteArrayOutputStream baos = new ByteArrayOutputStream();
            pdfDocument.save(baos);
            baos.toByteArray();
            */
    }

    public byte[] generateSimplePdfAsByteArray() throws IOException {
        PDDocument document = createNewSimplePdf();
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        document.save(baos);
        byte[] rawBytes = baos.toByteArray();
        document.close();
        baos.close();
        return rawBytes;
    }
}

/*

File file = new File("path of the document")
PDDocument document = PDDocument.load(file);

*/
